CREATE TABLE learning_notes
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    technology_id BIGINT       NOT NULL,
    title         VARCHAR(255) NOT NULL,
    summary       VARCHAR(255),
    content       TEXT         NOT NULL,
    difficulty    VARCHAR(20)  NOT NULL,

    CONSTRAINT ck_learning_notes_difficulty
        CHECK (difficulty IN ('JUNIOR', 'MID', 'SENIOR'))
);